import fs from "fs-extra";
import path from "node:path";
import type { RenderedFile } from "../providers/types.js";
import { resolvePath } from "../config/paths.js";
import { createBackup } from "./backup.js";

export type WriteResult = {
  path: string;
  changed: boolean;
  skipped: boolean;
  backupPath?: string;
  warning?: string;
};

export const textStartMarker = "<!-- agenthub:start -->";
export const textEndMarker = "<!-- agenthub:end -->";
export const tomlStartMarker = "# agenthub:start";
export const tomlEndMarker = "# agenthub:end";

export async function writeRenderedFile(
  rendered: RenderedFile,
  backupRoot: string,
  timestamp = timestampForBackup()
): Promise<WriteResult> {
  const targetPath = resolvePath(rendered.path);
  const existing = (await fs.pathExists(targetPath)) ? await fs.readFile(targetPath, "utf8") : undefined;
  const next = prepareNextContent(rendered, existing);

  if (existing === next) {
    return { path: targetPath, changed: false, skipped: false };
  }

  await fs.ensureDir(path.dirname(targetPath));
  const backupPath = existing === undefined ? undefined : await createBackup(targetPath, backupRoot, timestamp);
  await fs.writeFile(targetPath, next, "utf8");
  return { path: targetPath, changed: true, skipped: false, backupPath };
}

export function prepareNextContent(rendered: RenderedFile, existing?: string): string {
  if (rendered.format === "json") {
    return mergeJsonContent(rendered, existing);
  }

  if (rendered.writeMode === "managed") {
    return managedContent(rendered.content);
  }

  return replaceAppendBlock(existing ?? "", rendered.content, rendered.format === "toml" ? "toml" : "text");
}

export function managedContent(content: string): string {
  return [
    "<!-- agenthub:managed -->",
    "<!-- generated by AgentHub -->",
    "<!-- source: ~/.agenthub -->",
    "<!-- do not edit manually -->",
    "",
    content.trimEnd(),
    ""
  ].join("\n");
}

export function replaceAppendBlock(existing: string, generated: string, markerKind: "text" | "toml" = "text"): string {
  const start = markerKind === "toml" ? tomlStartMarker : textStartMarker;
  const end = markerKind === "toml" ? tomlEndMarker : textEndMarker;
  const block = `${start}\n${generated.trimEnd()}\n${end}`;

  const startIndex = existing.indexOf(start);
  const endIndex = existing.indexOf(end);
  if (startIndex >= 0 && endIndex >= startIndex) {
    return `${existing.slice(0, startIndex)}${block}${existing.slice(endIndex + end.length)}`;
  }

  const separator = existing.trim().length > 0 ? "\n\n" : "";
  return `${existing.trimEnd()}${separator}${block}\n`;
}

export function mergeJsonContent(rendered: RenderedFile, existing?: string): string {
  const base = parseJsonObject(existing);
  const generated = parseJsonObject(rendered.content);
  const keys = rendered.managedKeys ?? Object.keys(generated);

  for (const key of keys) {
    base[key] = generated[key];
  }
  if (!("$schema" in base) && "$schema" in generated) {
    base.$schema = generated.$schema;
  }

  return `${JSON.stringify(base, null, 2)}\n`;
}

function parseJsonObject(content?: string): Record<string, unknown> {
  if (!content?.trim()) {
    return {};
  }
  const parsed = JSON.parse(content) as unknown;
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw new Error("JSON target must contain an object");
  }
  return parsed as Record<string, unknown>;
}

export function timestampForBackup(date = new Date()): string {
  return date.toISOString().replaceAll(":", "").replaceAll(".", "");
}
